### ISSUE TITLE
ValueError: Linear is expecting 2D arguments: [2, None, 50]  while 'python qrn.py'

### ISSUE THREAD

**Issue by SeekPoint** [yfletberliac/Mango#3]
with tf1.2 

(venv) ali-186590cc37a5:Mango$ python qrn.py
aname
('the value of ccc is  ', 'this is a string')
on func:test at file:andy_common.py #28
('the value of aname is  ', 111111)
qa1_single-supporting-fact
3242 (seed)
vocab = [u'.', u'?', u'Daniel', u'John', u'Mary', u'Sandra', u'Where', u'back', u'bathroom', u'bedroom', u'garden', u'hallway', u'is', u'journeyed', u'kitchen', u'moved', u'office', u'the', u'to', u'travelled', u'went']
X.shape = (1000, 10, 7)
Xq.shape = (1000, 4)
Y.shape = (1000, 22)
story_maxlen, query_maxlen = 10, 4
Traceback (most recent call last):
  File "qrn.py", line 542, in <module>
    model = RNN_Model(config)
  File "qrn.py", line 53, in __init__
    story_question_state = self.add_model(self.inputs_story, self.inputs_question)
  File "qrn.py", line 176, in add_model
    dtype=tf.float32)
  File "qrn.py", line 443, in custom_bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 546, in dynamic_rnn
    dtype=dtype)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 713, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2605, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2438, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2388, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 696, in _time_step
    skip_conditionals=True)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 177, in _rnn_step
    new_output, new_state = call_cell()
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 684, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/Users//ve_tf1.0_py2/venv/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 524, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/Users//Mango/qrn/qrncell.py", line 28, in __call__
    c = self._activation(linear(tf.concat(inputs, 1), self._num_units))
  File "/Users//Mango/qrn/qrncell.py", line 51, in linear
    raise ValueError("Linear is expecting 2D arguments: %s" % str(shape))
ValueError: Linear is expecting 2D arguments: [2, None, 50]
(venv) ali-186590cc37a5:Mango$

**Comment by yfletberliac** [comment]
I forgot to push the right script version, sorry. It should be fixed now, please let me know if you encounter more issues.
